- src/codegen/operations.rs
- src/opcodes.rs
- src/utils.rs
- tests/operations.rs
Closes #4
This PR implements the code generation for the [ADD](https://www.evm.codes/#01?fork=cancun) opcode.
> feat: implement ADD opcode

- src/codegen/operations.rs
- src/opcodes.rs
- tests/operations.rs
Closes #57 
This PR implements the code generation for the [POP](https://www.evm.codes/#50?fork=cancun) opcode.
> feat: implement POP opcode

- README.md
This PR adds documentation on how to inspect the compiled artifacts, and debugging them with `lldb`.
> docs: add readme section about debugging with lldb

- src/codegen/operations.rs
- src/opcodes.rs
- tests/operations.rs
Closes #5 
This PR implements the code generation for the MUL opcode
> feat: implement MUL opcode

- README.md
This PR adds some pretty badges to the readme.
> docs: add some badges to readme

- README.md
- src/codegen/operations.rs
- src/program.rs
- src/utils.rs
- tests/operations.rs
Closes #9 
This PR implements the MOD opcode.
> feat: implement MOD opcode

- README.md
- src/codegen/operations.rs
- src/program.rs
- tests/operations.rs
Closes #23 
This PR handles the implementation of XOR opcode
> Implement XOR Opcode

- src/codegen/operations.rs
- src/program.rs
- tests/operations.rs
Closes #62 
This PR implements the code generation for the [JUMP](https://www.evm.codes/#56?fork=cancun) opcode.
> feat: implement JUMP opcode

- src/codegen/operations.rs
- tests/operations.rs
Closes #137 
This PR adds a checking step before executing the XOR opcode.
> feat: Opcode XOR (gas count)

- src/codegen/operations.rs
- tests/operations.rs
Closes #163 
This PR implements the gas consumption for the PC opcode.
> Add gas consumption to PC

- README.md
Moves REVERT and RETURN to implemented
> move REVERT and RETURN to implemented

- README.md
- src/codegen/operations.rs
- src/constants.rs
- src/program.rs
- src/utils.rs
- tests/operations.rs
Closes #70 
This PR handles the implementation of the MCOPY opcode
> feat: Opcode MCOPY

- src/codegen/operations.rs
Closes #239 
This PR refactors ISZERO opcode to remove the branch that is currently being made.
> Refactor ISZERO opcode to remove branch.

- README.md
Didn't want this fix to be lost. Good catch @mahmudsudo !
> docs: fix Linux LLVM setup instructions in readme

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- Cargo.lock
- rust-toolchain.toml
This PR update the rust version to 1.79.
> Update to Rust 1.79

- src/syscall.rs
> fix: remove allow(improper_ctypes) attributes from syscalls

- src/codegen/operations.rs
- src/constants.rs
- tests/operations.rs
closes #206 
This PR computes the dynamic gas cos for the EXP opcode
> feat: Dynamic gas EXP

- CODEOWNERS
I don't have any knowledge about mlir 😅
> Remove `mpaulucci` from codeowners

- src/codegen/operations.rs
- src/constants.rs
- tests/operations.rs
Closes #293 
This PR adds gas consumption to the NOT operation, with tests.
> Add gas consumption to NOT operation

- README.md
- bench/revm_comparison/src/lib.rs
- src/codegen/context.rs
- src/codegen/operations.rs
- src/context.rs
- src/executor.rs
- src/lib.rs
- src/main.rs
- src/program.rs
- src/syscall.rs
- src/utils.rs
- tests/evm.rs
- tests/operations.rs
This PR implements the opcode `STATICCALL` with tests.
Closes #81
> Implement opcode `STATICCALL`

- src/constants.rs
- src/precompiles.rs
- src/syscall.rs
- tests/evm.rs
Closes #342 
This PR adds the implementation for the modexp precompile.
> feat: implement `modexp` precompile 

- src/syscall.rs
- tests/ef_tests.rs
- tests/evm.rs
Closes https://github.com/lambdaclass/evm_mlir/issues/312
This PR try to fix the stRefundTest and the issue for limiting gas refunds to 1/5 of the total gas used
- Added a limit of 1/5 of the total gas used to be refunded
- New tests for this functionality
- Updated old tests for the new gas cap
> Refund tests

- README.md
Closes #403.
Rewrites the section while adding the eth tests download step.
> docs: enhance testing section in README

- src/syscall.rs
Closes #326 
Just a small change following the issue description
> Fixed log address bug

- .github/workflows/ci.yml
- Cargo.toml
- Makefile
- tests/ef_tests.rs
- tests/ef_tests_executor/mod.rs
- tests/ef_tests_executor/test_utils.rs
- tests/time_consuming_test.rs
Closes #416 
This PR will change the ci for running the EF tests in 2 different workers
> CI parallelization

- Cargo.lock
- Update dependencies in `cargo.lock` by running cargo update
> Update dependencies of project
